[build-system]
requires = ["hatchling >= 1.27"]
build-backend = "hatchling.build"

[project]
name = "chess-search"
version = "0.1.0"
requires-python = ">=3.10"
maintainers = [
  {name = "Christopher Akiki", email = "christopher.akiki@gmail.com"}
]
description = "Chess position retrieval"
readme = "README.md"
license = "AGPL-3.0-or-later"
dependencies = [
    "chess",
    "pyroaring",
    "tqdm",
    "lmdb",
    "lark",
]

[project.optional-dependencies]
hf  = ["huggingface_hub"]
dev = ["pytest", "ruff"]

[tool.hatch.build.targets.wheel]
packages = ["src/chess_search"]

[tool.ruff]
line-length = 120
